### ISSUE TITLE
[Spanner] authentication issues should result in a user error

### ISSUE THREAD

**Issue by jadekler** [googleapis/python-spanner#4]
1. Copy paste code from https://cloud.google.com/spanner/docs/getting-started/python/
2. Run

... it hangs forever

3. ~Waste~ Spend hour struggling to figure out what is happening.
4. Figure out how to turn on http logging with,

    ```
    import logging

    logging.basicConfig(level=logging.DEBUG)
    ```
5. See:

    ```
    DEBUG:google.auth.transport.requests:Making request: POST https://oauth2.googleapis.com/token
    DEBUG:urllib3.connectionpool:https://oauth2.googleapis.com:443 "POST /token HTTP/1.1" 400 None
    ERROR:grpc._plugin_wrapping:AuthMetadataPluginCallback "<google.auth.transport.grpc.AuthMetadataPlugin object at 0x10d79d4a8>" raised exception!
    Traceback (most recent call last):
    File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/grpc/_plugin_wrapping.py", line 79, in __call__
        callback_state, callback))
    File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/google/auth/transport/grpc.py", line 77, in __call__
        callback(self._get_authorization_headers(context), None)
    File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/google/auth/transport/grpc.py", line 65, in _get_authorization_headers
        headers)
    File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/google/auth/credentials.py", line 122, in before_request
        self.refresh(request)
    File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/google/oauth2/service_account.py", line 322, in refresh
        request, self._token_uri, assertion)
    File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/google/oauth2/_client.py", line 145, in jwt_grant
        response_data = _token_endpoint_request(request, token_uri, body)
    File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/google/oauth2/_client.py", line 111, in _token_endpoint_request
        _handle_error_response(response_body)
    File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/google/oauth2/_client.py", line 61, in _handle_error_response
        error_details, response_body)
    google.auth.exceptions.RefreshError: ('invalid_grant: Not a valid email or user ID.', '{\n  "error": "invalid_grant",\n  "error_description": "Not a valid email or user ID."\n}')
    DEBUG:google.api_core.retry:Retrying due to 503 Getting metadata from plugin failed with error: ('invalid_grant: Not a valid email or user ID.', '{\n  "error": "invalid_grant",\n  "error_description": "Not a valid email or user ID."\n}'), sleeping 1.3s ...
    ```

This is an error that will never resolve. We should surface it to the user immediately.

Also: I have _no idea_ why this is a `503 UNAVAILABLE`. Why would it not be a `400 BAD REQUEST` or `401 UNAUTHORIZED`??

**Comment by larkee** [comment]
Not sure how to progress here. Seems like an issue in another library. Need to investigate further.

**Comment by larkee** [comment]
>Looks like it's a 400 at one point, which indicates some broken plumbing where it didn't surface properly?

The [auth library does not pass through the status error code](https://github.com/googleapis/google-auth-library-python/blob/master/google/oauth2/_client.py#L124) through to gRPC. However, gRPC would replace it with INTERNAL regardless. See [status conversion](https://github.com/grpc/grpc/blob/fc7233e8f0788b16f574e2f6ed7a174970ba35ef/src/core/lib/transport/status_conversion.cc#L71). 

It is still unclear as to why the client receives an UNAVAILABLE error.

**Comment by larkee** [comment]
This is not an issue with the client library, but with its dependencies. I have filed an issue with `grpc` and will monitor its progress. Since there is nothing to be done in the client library, I am closing this issue.
