### ISSUE TITLE
Insert an ARRAY<JSON> in Spanner table

### ISSUE THREAD

**Issue by roscheledp** [googleapis/python-spanner#598]
Hello. Is it possible to insert an ARRAY OF JSON in spanner table?

#### Environment details

  - OS type and version: Ubuntu 20.04
  - Python version: 3.8.10
  - pip version: 21.1.2
  - `google-cloud-spanner` version: 3.10.0

#### Steps to reproduce

  1. Create a data like this:
```json
data = {
    "customer_id": "1",
    "coupons": [
        {
            "coupon_data": {
                "header": {"id": "123"},
                "name": "Cupom xpto",
                "description": "dahbskdhabsk",
                "code": "ABC123",
                "products": ["105106.15616.156", "48549.4984978"],
                "price": "10.9",
                "qty_burn_total": 10,
                "qty_burn_per_customer": 3,
                "resources":
                    [
                        {"img1": "img_url"},
                        {"img2": "img_url"},
                        {"img3": "img_url"},
                        {"img4": "img_url"},
                    ],
                "priority": 15,
                "tab": "Para você",
                "store_list_ids": ["sl1_id", "sl2_id", "sl3_id"],
                "coupom_expiration": "2022-01-01",
                "qrcode_expiration": "5",
                "flags": ["Frango", "ABC", "XYZ"]
            },
            "campaign_id": "y",
        },
        {
            "coupon_data": {
                "header": {"id": "444"},
                "name": "Coupon name",
                "description": "5das65d4as6d54asd",
                "code": "ABC999",
                "products": ["105106.1212", "123458.54987"],
                "price": "12.9",
                "qty_burn_total": 10,
                "qty_burn_per_customer": 3,
                "resources":
                    [
                        {"img1": "img_url"},
                        {"img2": "img_url"},
                        {"img3": "img_url"},
                        {"img4": "img_url"},
                    ],
                "priority": 12,
                "tab": "Frangos",
                "store_list_ids": ["sl1_id", "sl2_id", "sl3_id"],
                "coupom_expiration": "2022-01-01",
                "qrcode_expiration": "5",
                "flags": ["Frango", "ABC", "XYZ"]
            },
            "campaign_id": "x",
        }
    ]
}
```
  2. Pass this data in the `insert` parameter of SpannerRepository().insert(data)

#### Code example

```python
from google.cloud.spanner import Client
from google.cloud.spanner_v1.transaction import Transaction


class SpannerRepository:

    def __init__(self):
        self.client = Client()
        self.instance = self.client.instance("crm-coupons-teste")
        self.session = Session(database=self.instance.database("customer_coupons_info_test"),
                               labels={"session": "meu-teste"})
        self.session.create()
        self.transaction = Transaction(session=self.session)

        self.database = self.instance.database("customer_coupons_info_test")

    def get_instances(self):
        instances = self.client.list_instances()
        print(instances)

    def create_table(self, database_id=MY_DATABSE):
        database = self.instance.database(database_id)
        operation = database.update_ddl([
            """CREATE TABLE customer_coupons (
                    customer_id STRING(MAX) NOT NULL,
                    coupons ARRAY<JSON>,
                ) PRIMARY KEY(customer_id)"""
        ])

        return operation

    def insert(self, document):

        self.transaction.insert(
            table="customer_coupons",
            columns=["customer_id", "coupons"],
            values=[
                document["customer_id"], document["coupons"]
            ]
        )
        self.transaction.commit()

        return 'ok'
```

#### Stack trace
```
Traceback (most recent call last):
  File "/snap/pycharm-community/252/plugins/python-ce/helpers/pydev/pydevd.py", line 1483, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/snap/pycharm-community/252/plugins/python-ce/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/joao/edeploy/bk-crm-coupons-writer-function/main.py", line 102, in <module>
    run(event, "oi")
  File "/home/joao/edeploy/bk-crm-coupons-writer-function/main.py", line 35, in run
    result = save_document(document)
  File "/home/joao/edeploy/bk-crm-coupons-writer-function/service.py", line 8, in save_document
    result = repository.insert(document)
  File "/home/joao/edeploy/bk-crm-coupons-writer-function/repository/spanner_repository.py", line 30, in insert
    self.transaction.insert(
  File "/home/joao/edeploy/bk-crm-coupons-writer-function/venv/lib/python3.8/site-packages/google/cloud/spanner_v1/batch.py", line 61, in insert
    self._mutations.append(Mutation(insert=_make_write_pb(table, columns, values)))
  File "/home/joao/edeploy/bk-crm-coupons-writer-function/venv/lib/python3.8/site-packages/google/cloud/spanner_v1/batch.py", line 207, in _make_write_pb
    table=table, columns=columns, values=_make_list_value_pbs(values)
  File "/home/joao/edeploy/bk-crm-coupons-writer-function/venv/lib/python3.8/site-packages/google/cloud/spanner_v1/_helpers.py", line 193, in _make_list_value_pbs
    return [_make_list_value_pb(row) for row in values]
  File "/home/joao/edeploy/bk-crm-coupons-writer-function/venv/lib/python3.8/site-packages/google/cloud/spanner_v1/_helpers.py", line 193, in <listcomp>
    return [_make_list_value_pb(row) for row in values]
  File "/home/joao/edeploy/bk-crm-coupons-writer-function/venv/lib/python3.8/site-packages/google/cloud/spanner_v1/_helpers.py", line 181, in _make_list_value_pb
    return ListValue(values=[_make_value_pb(value) for value in values])
  File "/home/joao/edeploy/bk-crm-coupons-writer-function/venv/lib/python3.8/site-packages/google/cloud/spanner_v1/_helpers.py", line 181, in <listcomp>
    return ListValue(values=[_make_value_pb(value) for value in values])
  File "/home/joao/edeploy/bk-crm-coupons-writer-function/venv/lib/python3.8/site-packages/google/cloud/spanner_v1/_helpers.py", line 139, in _make_value_pb
    return Value(list_value=_make_list_value_pb(value))
  File "/home/joao/edeploy/bk-crm-coupons-writer-function/venv/lib/python3.8/site-packages/google/cloud/spanner_v1/_helpers.py", line 181, in _make_list_value_pb
    return ListValue(values=[_make_value_pb(value) for value in values])
  File "/home/joao/edeploy/bk-crm-coupons-writer-function/venv/lib/python3.8/site-packages/google/cloud/spanner_v1/_helpers.py", line 181, in <listcomp>
    return ListValue(values=[_make_value_pb(value) for value in values])
  File "/home/joao/edeploy/bk-crm-coupons-writer-function/venv/lib/python3.8/site-packages/google/cloud/spanner_v1/_helpers.py", line 169, in _make_value_pb
    raise ValueError("Unknown type: %s" % (value,))
ValueError: Unknown type: {'coupon_data': {'header': {'id': '123'}, 'name': 'Cupom xpto', 'description': 'dahbskdhabsk', 'code': 'ABC123', 'products': ['105106.15616.156', '48549.4984978'], 'price': '10.9', 'qty_burn_total': 10, 'qty_burn_per_customer': 3, 'resources': [{'img1': 'img_url'}, {'img2': 'img_url'}, {'img3': 'img_url'}, {'img4': 'img_url'}], 'priority': 15, 'tab': 'Para você', 'store_list_ids': ['sl1_id', 'sl2_id', 'sl3_id'], 'coupom_expiration': '2022-01-01', 'qrcode_expiration': '5', 'flags': ['Frango', 'ABC', 'XYZ']}, 'campaign_id': 'y'}
```

Making sure to follow these steps will guarantee the quickest resolution possible.

Thanks!

**Comment by larkee** [comment]
Hi there,

Currently, JSON values are expected to be strings. It should work if you update your `insert` method like so:
```
import json

    def insert(self, document):
        coupons = list(map(json.dumps, document["coupons"]))
        self.transaction.insert(
            table="customer_coupons",
            columns=["customer_id", "coupons"],
            values=[
                document["customer_id"], coupons
            ]
        )
        self.transaction.commit()

        return 'ok'
```

I noticed in your code example that you are creating your own `Session` and `Transaction` in the setup of `SpannerRepository`. This is not recommended for a couple of reasons. Firstly, if you create the session you are responsible for cleaning it up (i.e. deleting it). If the session is not correctly cleaned up, it is considered leaked and leaked sessions can have an impact on performance. Secondly, you are bypassing the `Database` session pool. This session pool not only handles the clean up, but also ensures sessions are reused and allows for multiple sessions to be used at once.

The preferred way to implement your code sample would be:
```
import json

from google.cloud.spanner import Client
from google.cloud.spanner_v1.transaction import Transaction


class SpannerRepository:

    def __init__(self):
        self.client = Client()
        self.instance = self.client.instance("crm-coupons-teste")
        session_pool = BurstyPool(labels={"session": "meu-teste"})  # This is the default session pool type.
        self.database = self.instance.database("customer_coupons_info_test", pool=session_pool)

...
    # Insert using Batch (write-only transaction)
    def insert_w_batch(self, document):
        with self.database.batch() as batch:
            coupons = list(map(json.dumps, document["coupons"]))
            batch.insert(
                table="customer_coupons",
                columns=["customer_id", "coupons"],
                values=[
                    document["customer_id"], coupons
                ]
            )
        # Commit will be called automatically when exiting the with block.

        return 'ok'


    # Insert using Transaction (read-write transaction)
    def insert_w_transaction(self, document):
        def insert(transaction, document):
            coupons = list(map(json.dumps, document["coupons"]))
            transaction.insert(
                table="customer_coupons",
                columns=["customer_id", "coupons"],
                values=[
                    document["customer_id"], coupons
                ]
            )

        # This method will create a transaction, run the given function, and call commit.
        database.run_in_transaction(insert, document)
        return 'ok'
```  
You can choose whether you would prefer to use a `Batch` or a `Transaction` depending on your use case.

Please let me know if you have any questions about this :+1:

**Comment by roscheledp** [comment]
Thanks for your reply @larkee !
I'm following your example but when running the `insert_w_batch` with `BurstyPool` I get this error below when the batch start in `with self.database.batch() as batch:`. 
So, I'm still confuse about how to set up a session. Can you help me?

```
Traceback (most recent call last):
  File "/home/joao/edeploy/bk-crm-coupons-writer-function/venv/lib/python3.8/site-packages/google/cloud/spanner_v1/pool.py", line 272, in get
    session = self._sessions.get_nowait()
  File "/usr/lib/python3.8/queue.py", line 198, in get_nowait
    return self.get(block=False)
  File "/usr/lib/python3.8/queue.py", line 167, in get
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/joao/edeploy/bk-crm-coupons-writer-function/venv/lib/python3.8/site-packages/google/api_core/grpc_helpers.py", line 66, in error_remapped_callable
    return callable_(*args, **kwargs)
  File "/home/joao/edeploy/bk-crm-coupons-writer-function/venv/lib/python3.8/site-packages/grpc/_channel.py", line 946, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/home/joao/edeploy/bk-crm-coupons-writer-function/venv/lib/python3.8/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
    raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
	status = StatusCode.INVALID_ARGUMENT
	details = "Invalid CreateSession request."
	debug_error_string = "{"created":"@1632931734.159025517","description":"Error received from peer ipv6:[2800:3f0:4001:825::200a]:443","file":"src/core/lib/surface/call.cc","file_line":1069,"grpc_message":"Invalid CreateSession request.","grpc_status":3}"
>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/joao/edeploy/bk-crm-coupons-writer-function/main.py", line 103, in <module>
    r = run(event, "oi")
  File "/home/joao/edeploy/bk-crm-coupons-writer-function/main.py", line 35, in run
    result = save_document(document)
  File "/home/joao/edeploy/bk-crm-coupons-writer-function/service.py", line 8, in save_document
    result = repository.insert_or_update_w_batch(document)
  File "/home/joao/edeploy/bk-crm-coupons-writer-function/repository/spanner_repository.py", line 71, in insert_or_update_w_batch
    with self.database.batch() as batch:
  File "/home/joao/edeploy/bk-crm-coupons-writer-function/venv/lib/python3.8/site-packages/google/cloud/spanner_v1/database.py", line 803, in __enter__
    session = self._session = self._database._pool.get()
  File "/home/joao/edeploy/bk-crm-coupons-writer-function/venv/lib/python3.8/site-packages/google/cloud/spanner_v1/pool.py", line 275, in get
    session.create()
  File "/home/joao/edeploy/bk-crm-coupons-writer-function/venv/lib/python3.8/site-packages/google/cloud/spanner_v1/session.py", line 123, in create
    session_pb = api.create_session(request=request, metadata=metadata,)
  File "/home/joao/edeploy/bk-crm-coupons-writer-function/venv/lib/python3.8/site-packages/google/cloud/spanner_v1/services/spanner/client.py", line 459, in create_session
    response = rpc(request, retry=retry, timeout=timeout, metadata=metadata,)
  File "/home/joao/edeploy/bk-crm-coupons-writer-function/venv/lib/python3.8/site-packages/google/api_core/gapic_v1/method.py", line 142, in __call__
    return wrapped_func(*args, **kwargs)
  File "/home/joao/edeploy/bk-crm-coupons-writer-function/venv/lib/python3.8/site-packages/google/api_core/retry.py", line 283, in retry_wrapped_func
    return retry_target(
  File "/home/joao/edeploy/bk-crm-coupons-writer-function/venv/lib/python3.8/site-packages/google/api_core/retry.py", line 190, in retry_target
    return target()
  File "/home/joao/edeploy/bk-crm-coupons-writer-function/venv/lib/python3.8/site-packages/google/api_core/grpc_helpers.py", line 68, in error_remapped_callable
    raise exceptions.from_grpc_error(exc) from exc
google.api_core.exceptions.InvalidArgument: 400 Invalid CreateSession request.

Process finished with exit code 1
```
